services:
  - type: web
    name: ml-fastapi-deploy
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: ./start.sh
    plan: free
    branch: main
    autoDeploy: true
